"""added like-dislike and state

Revision ID: 396ef14df4bd
Revises: a1076c645373
Create Date: 2023-05-10 20:37:10.492748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '396ef14df4bd'
down_revision = 'a1076c645373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offer', sa.Column('scraping_date', sa.DateTime(), nullable=True))
    op.add_column('job_offer', sa.Column('like_dislike', sa.Integer(), nullable=True))
    op.add_column('job_offer', sa.Column('state', sa.Integer(), nullable=True))
    op.drop_column('job_offer', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offer', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('job_offer', 'state')
    op.drop_column('job_offer', 'like_dislike')
    op.drop_column('job_offer', 'scraping_date')
    # ### end Alembic commands ###
