"""first version

Revision ID: af28b7a1927d
Revises: 
Create Date: 2023-04-09 20:54:49.342627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af28b7a1927d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('offer_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('contract', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_offer')
    # ### end Alembic commands ###
