"""all tables

Revision ID: c9af9a717ae2
Revises: 9ba49e08846d
Create Date: 2023-05-01 20:31:29.315790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9af9a717ae2'
down_revision = '9ba49e08846d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('web', sa.String(), nullable=True),
    sa.Column('reputation', sa.Float(), nullable=True),
    sa.Column('n_employees', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('technology',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('interview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('text_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offer.id'], name='interview_job_offer_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'job_offer', ['link'])
    op.create_unique_constraint(None, 'web', ['name'])
    op.create_unique_constraint(None, 'web', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web', type_='unique')
    op.drop_constraint(None, 'web', type_='unique')
    op.drop_constraint(None, 'job_offer', type_='unique')
    op.drop_table('interview')
    op.drop_table('technology')
    op.drop_table('company')
    # ### end Alembic commands ###
