"""web not null

Revision ID: 14559d10b1d1
Revises: c9af9a717ae2
Create Date: 2023-05-01 20:50:30.790947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14559d10b1d1'
down_revision = 'c9af9a717ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_offer', 'web',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_offer', 'web',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
