"""company foreignkey

Revision ID: a1076c645373
Revises: 14559d10b1d1
Create Date: 2023-05-01 20:53:20.036567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1076c645373'
down_revision = '14559d10b1d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offer', 'company')
    op.add_column('job_offer', sa.Column('company', sa.Integer(), nullable=False))
    op.create_foreign_key('job_offer_company_id_fkey', 'job_offer', 'company', ['company'], ['id'], onupdate='CASCADE',
                          ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offer', 'company')
    op.add_column('company', sa.String(), nullable=False)
    op.drop_constraint('job_offer_company_id_fkey', 'job_offer', type_='foreignkey')
    # ### end Alembic commands ###
