"""new table job-tech

Revision ID: e11ddaf724b8
Revises: 396ef14df4bd
Create Date: 2023-05-21 22:35:19.770073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11ddaf724b8'
down_revision = '396ef14df4bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_tech',
    sa.Column('offer_id', sa.BIGINT(), nullable=False),
    sa.Column('tech_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offer.id'], name='job_tech_offer_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tech_id'], ['technology.id'], name='job_tech_technology_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'tech_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_tech')
    # ### end Alembic commands ###
